name: core26
# version: "26"
adopt-info: bootstrap
summary: Runtime environment based on Ubuntu 26.04
description: |
  The base snap based on the Ubuntu 26.04 release.
confinement: strict
type: base
build-base: devel
grade: devel
assumes: [snapd2.55.5]

parts:
  # TODO: rewrite this once all slices are upstreamed to use chisel slices
  # directly from canonical, instead of our own chisel-releases repo.
  chisel-libs:
    plugin: nil
    build-packages:
      - golang
      - file
    source: https://github.com/Meulengracht/chisel-releases.git
    source-type: git
    source-branch: ubuntu-core-26.04
    override-build: |
      go install github.com/canonical/chisel/cmd/chisel@latest
      
      # Define the system utilities that we want to include in the base
      # These are the ones where we can probably slim down the number of binaries
      # later on, but for now we include them all to ensure maximum compatibility.
      UTILS=(
        apparmor_bins
        bash_bins
        bzip2_scripts
        coreutils-from-uutils_bins
        diffutils_bins
        dosfstools_bins
        debianutils_which
        debianutils_ischroot
        debianutils_run-parts
        file_bins
        gdbserver_bins
        gnu-coreutils_bins
        gnutls-bin_bins
        gpgv_bins
        grep_bins
        gzip_scripts
        hostname_bins
        iptables_bins
        iputils-ping_bins
        less_bins
        login_bins
        mawk_bins
        ncurses-bin_bins
        polkitd_bins
        rfkill_bins
        sed_bins
        sudo_bins
        squashfs-tools_bins
        tar_bins
        util-linux_bins
        util-linux-extra_bins
        vim-tiny_bins
      )

      # Define the system libraries and services that we want to include in the base
      # 
      SLICES=(
        apparmor_extras
        base-files_motd
        base-files_release-info
        bash-completion_config
        bash-completion_completions
        ca-certificates_data
        cloud-init_bins
        cracklib-runtime_bins
        cryptsetup_bins
        cryptsetup-bin_bins
        dbus_services
        dbus-user-session_services
        distro-info-data_data
        dmsetup_rules
        e2fsprogs_services
        fonts-ubuntu_all
        fonts-ubuntu_config
        finalrd_services
        kmod_bins
        kmod_config

        libc6_config
        libc6_gconv
        libc-bin_iconv
        libc-bin_nsswitch
        libc-bin_ldconfig
        libc-bin_locale
        libc-bin_getconf
        libc-bin_getent

        libpam-modules_config
        libpam-modules_pam-config
        libpam-pwquality_pam-config
        libpam-modules-bin_standard
        libpam-modules-bin_extrausers
        libpam-modules-bin_namespace
        libpam-modules-bin_timestamp
        libpam-systemd_libs
        libengine-pkcs11-openssl_libs
        libgnutls30t64_config
        libopts25_libs
        libp11-3t64_libs
        libnss-mdns_mdns4-minimal
        libnss-extrausers_libs
        libpam-pwquality_libs
        libpciaccess0_libs
        libwrap0_host-files
        locales_standard

        ncurses-base_terminfo

        openssh-client_config
        openssh-client_services
        openssh-server_bins
        openssh-server_config
        openssh-server_services
        openssl_bins
        opensc_bins
        p11-kit_bins
        passwd_pam-config
        polkitd_services
        plymouth_bins
        plymouth-label-ft_libs
        procps_config

        udev_services
        util-linux_services
        systemd_extras
        systemd_kernel-parameters
        systemd_tpm2
        systemd_standard
        systemd_user-services
        systemd-bootchart_services
        systemd-coredump_bins
        systemd-cryptsetup_bins
        systemd-resolved_bins
        systemd-sysv_bins
        systemd-timesyncd_services
        systemd-zram-generator_services
        
        tzdata_zoneinfo
        wpasupplicant_services
      )

      # TODO: not sure about FIPS yet, this will have to come later, chisel has builtin
      # support for ESM, meaning it's something we can request chisel to do for us.
      # if [[ ${SNAP_FIPS_BUILD+x} ]]; then
      #   # Ensure vital crypt packages are refreshed / downgraded and downloaded
      #   # from the FIPS ppa. This should also contain openssh-server, but we already
      #   # have that one listed above.
      #   SLICES+=(libgcrypt20 libgnutls30t64 openssl-fips-module-3 ssh)
      # fi
      
      # add architecture specific slices
      case "$(dpkg --print-architecture)" in
          amd64|i386)
              SLICES+=(secureboot-db_services)
              ;;
          riscv64)
              SLICES+=(gdbserver_bins systemd-bootchart_services)
              ;;
      esac

      # create the rootfs directory we install slices into
      mkdir -p "${CRAFT_STAGE}"/base

      # Cut the initial slices into the rootfs
      # TODO: remove --ignore=unstable when chisel 26.04 is stable
      chisel cut --ignore=unstable \
        --release="${CRAFT_PART_SRC}" \
        --root "${CRAFT_STAGE}"/base \
        "${SLICES[@]}" "${UTILS[@]}" \
        base-files_chisel

      # Cut foreign libraries we also need
      # TODO: remove --ignore=unstable when chisel 26.04 is stable
      case "$(dpkg --print-architecture)" in
          amd64)
              chisel cut --ignore=unstable \
                --arch=i386 \
                --release="${CRAFT_PART_SRC}" \
                --root "${CRAFT_STAGE}"/base \
                libnss-mdns_mdns4-minimal libc6_libs libc6_gconv libc6_config libgcc-s1_libs
              ;;
          arm64)
              chisel cut --ignore=unstable \
                --arch=armhf \
                --release="${CRAFT_PART_SRC}" \
                --root "${CRAFT_STAGE}"/base \
                libnss-mdns_mdns4-minimal libc6_libs libc6_gconv libc6_config libgcc-s1_libs
              ;;
      esac
      
      # https://documentation.ubuntu.com/chisel/en/latest/reference/manifest/
      # chisel automatically generates a manifest for the cut slices here:
      # $rootfs/var/lib/chisel/manifest.wall
      # this is zstd compressed, and must therefor be uncompressed
      # unzstd ./manifest.wall -o manifest.json

  snapd-files:
    plugin: nil
    source: .
    build-packages:
      - snapd
    after:
      - chisel-libs
    override-build: |
      mkdir -p "${CRAFT_STAGE}"/base/usr/lib/systemd/system-generators
      cp /usr/lib/systemd/system-generators/snapd-generator "${CRAFT_STAGE}"/base/usr/lib/systemd/system-generators/snapd-generator

  nvidia-deps:
    plugin: nil
    source: .
    build-packages:
      - nvidia-kernel-common-570
    after:
      - chisel-libs
    override-build: |
      case "$(dpkg --print-architecture)" in
          amd64|arm64)
              # Copy nvidia config files and dependencies (sources for this come from
              # Canonical, not from Nvidia, see
              # https://github.com/canonical/nvidia-graphics-drivers).
              mkdir -m 755 -p "${CRAFT_STAGE}"/base/usr/sbin
              cp /sbin/ub-device-create "${CRAFT_STAGE}"/base/usr/sbin/ub-device-create
              
              mkdir -m 755 -p "${CRAFT_STAGE}"/base/usr/lib/udev/rules.d
              cp /lib/udev/rules.d/71-nvidia.rules "${CRAFT_STAGE}"/base/usr/lib/udev/rules.d/71-nvidia.rules
              
              mkdir -m 755 -p "${CRAFT_STAGE}"/base/etc/modprobe.d
              cp /etc/modprobe.d/nvidia-graphics-drivers-kms.conf "${CRAFT_STAGE}"/base/etc/modprobe.d/nvidia-graphics-drivers-kms.conf
              ;;
      esac

  splash-theme:
    plugin: dump
    source: https://github.com/snapcore/plymouth-theme-ubuntu-core.git
    source-type: git
    organize:
      ubuntu-core: usr/share/plymouth/themes/ubuntu-core
  
  bootstrap:
    after:
      - chisel-libs
      - snapd-files
      - nvidia-deps
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - distro-info
      - python3-debian
      - python3-requests
      - python3-yaml
    # to generate changelogs, it's own snap need to be present,
    # obviously for new core bases this cannot be the case, and
    # we need to wait until the first release with introducing
    # changelogs.
    # TODO change to core26 when available
    build-snaps:
      - core24=latest/beta
    override-pull: |
      craftctl default

      date_tag=$(./get-version.sh)

      # detect whether we are doing a fips build on LP
      if git remote get-url origin | grep "fips"; then
        craftctl set version="$date_tag"+fips
        echo "SNAP_FIPS_BUILD=1" > ./.fips-env
        echo "SNAP_BUILD_NAME=core26-fips" >> ./.fips-env
      else
        craftctl set version=$date_tag
        rm -f ./.fips-env
      fi
    override-prime: |
      craftctl default

      # run all the hooks
      cd ${CRAFT_PART_SRC} && make hooks DESTDIR=${CRAFT_PRIME}

      # ensure build-in tests are run
      cd ${CRAFT_PART_SRC} && make test TESTDIR=${CRAFT_PRIME}
