name: core26
# version: "26"
adopt-info: bootstrap
summary: Runtime environment based on Ubuntu 26.04
description: |
  The base snap based on the Ubuntu 26.04 release.
confinement: strict
type: base
build-base: devel
grade: devel
assumes: [snapd2.55.5]

parts:
  base:
    plugin: nil
    source: keyrings
    build-packages:
      - wget
    build-environment:
      #- RELEASE: "26.04"
      #- BASE: ubuntu-base-${RELEASE}${DOT_RELEASE:+.$DOT_RELEASE}-base-${CRAFT_ARCH_BUILD_FOR}.tar.gz
      #- DIR_URL: https://cdimage.ubuntu.com/ubuntu-base/releases/${RELEASE}/release
      - BASE: resolute-base-${CRAFT_ARCH_BUILD_FOR}.tar.gz
      - DIR_URL: https://cdimage.ubuntu.com/ubuntu-base/daily/current

      - URL: ${DIR_URL}/${BASE}
      - SHA256: ${DIR_URL}/SHA256SUMS
      - SIG: ${SHA256}.gpg
    override-pull: |
      craftctl default
      wget -q "${SHA256}" "${SIG}" "${URL}"
      gpg --no-default-keyring \
          --keyring ./cd-image-keying.gpg \
          --verify SHA256SUMS.gpg SHA256SUMS
      awk -v "file=${BASE}" '$2=="*"file' SHA256SUMS | sha256sum -c
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}/base"
      tar -x --xattrs-include=* -f "${BASE}" -C "${CRAFT_PART_INSTALL}/base"
    override-stage: |
      rm -rf "${CRAFT_STAGE}/base"
      craftctl default
    override-prime: |
      # Do nothing
  splash-theme:
    plugin: dump
    source: https://github.com/snapcore/plymouth-theme-ubuntu-core.git
    source-type: git
    organize:
      ubuntu-core: usr/share/plymouth/themes/ubuntu-core
      copyright: usr/share/doc/plymouth-theme-ubuntu-core/copyright
    stage:
      - -README.md
  bootstrap:
    after:
      - base
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - distro-info
      - python3-debian
      - python3-requests
      - python3-yaml
    # to generate changelogs, it's own snap need to be present,
    # obviously for new core bases this cannot be the case, and
    # we need to wait until the first release with introducing
    # changelogs.
    # TODO change to core26 when available
    build-snaps:
      - core24=latest/beta
    override-pull: |
      craftctl default

      date_tag=$(./get-version.sh)

      # detect whether we are doing a fips build on LP
      if git remote get-url origin | grep "fips"; then
        craftctl set version="$date_tag"+fips
        echo "SNAP_FIPS_BUILD=1" > ./.fips-env
        echo "SNAP_BUILD_NAME=core26-fips" >> ./.fips-env
      else
        craftctl set version=$date_tag
        rm -f ./.fips-env
      fi
    override-prime: |
      craftctl default
      # ensure build-in tests are run
      cd ${CRAFT_PART_SRC} && make test TESTDIR=${CRAFT_PRIME}
