name: core22
# version: "22"
adopt-info: bootstrap
summary: Runtime environment based on Ubuntu 22.04
description: |
  The base snap based on the Ubuntu 22.04 release.
confinement: strict
type: base
build-base: core22
grade: stable
assumes: [snapd2.55.5]

parts:
  probert-deb:
    plugin: nil
    source: https://github.com/canonical/probert.git
    source-type: git
    # following branch server/jammy
    source-commit: 253acbe1480fba69d12d6e72f53412da79e27410
    override-pull: |
      craftctl default
      # install build dependencies
      export DEBIAN_FRONTEND=noninteractive
      export DEBCONF_NONINTERACTIVE_SEEN=true
      apt-get build-dep -y ./
    override-build: |
      # unset the LD_FLAGS and LD_LIBRARY_PATH vars that snapcraft sets for us
      # as those will point to the $CRAFT_STAGE which on re-builds will
      # contain things like libc and friends that confuse the debian package
      # build system
      # TODO: should we unset $PATH to not include $CRAFT_STAGE too?
      unset LD_FLAGS
      unset LD_LIBRARY_PATH
      # run the real build (but just build the binary package, and don't
      # bother compressing it too much)
      dpkg-buildpackage -b -uc -us -Zgzip -zfast
      cp ../probert-{network,common}*.deb $CRAFT_PART_INSTALL
    stage:
      - -probert*.deb
    # XXX: Dirty hacks to enable building core22 on non-focal systems.
    # See below for details.
    override-prime: |
      craftctldir="$(dirname "$(command -v craftctl)")"
      unset LD_LIBRARY_PATH;
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
      # ensure craftctl is found, see
      # https://github.com/snapcore/snapcraft/pull/2251
      export PATH="$PATH:$craftctldir"
      craftctl default
  consoleconf-deb:
    after:
      - probert-deb
    plugin: nil
    source: https://github.com/canonical/subiquity.git
    source-type: git
    # following branch server/jammy
    source-commit: 8f9f97c69bb36048ea4c9e16be34bca3ac141771
    override-pull: |
      craftctl default
      # install build dependencies
      export DEBIAN_FRONTEND=noninteractive
      export DEBCONF_NONINTERACTIVE_SEEN=true
      apt-get build-dep -y ./
    override-build: |
      # unset the LD_FLAGS and LD_LIBRARY_PATH vars that snapcraft sets for us
      # as those will point to the $CRAFT_STAGE which on re-builds will
      # contain things like libc and friends that confuse the debian package
      # build system
      # TODO: should we unset $PATH to not include $CRAFT_STAGE too?
      unset LD_FLAGS
      unset LD_LIBRARY_PATH
      # run the real build (but just build the binary package, and don't
      # bother compressing it too much)
      dpkg-buildpackage -b -uc -us -Zgzip -zfast
      cp ../console-conf_*.deb ../subiquitycore_*.deb $CRAFT_PART_INSTALL
    stage:
      - -console-conf_*.deb
      - -subiquitycore_*.deb
    # XXX: Dirty hacks to enable building core22 on non-focal systems.
    # See below for details.
    override-prime: |
      craftctldir="$(dirname "$(command -v craftctl)")"
      unset LD_LIBRARY_PATH;
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
      # ensure craftctl is found, see
      # https://github.com/snapcore/snapcraft/pull/2251
      export PATH="$PATH:$craftctldir"
      craftctl default
  bootstrap:
    after:
      - consoleconf-deb
    plugin: make
    source: .
    build-packages:
      - shellcheck
      - wget
      - distro-info
    build-snaps:
      # XXX: Temporarily force using snapd from edge for building the snap,
      # as there seems to be an issue with the current snapd on impish, causing
      # core-dumps of the mksquashfs call (via `snap pack`).
      - snapd/latest/edge
    # XXX: Dirty hacks to enable building core22 on non-jammy systems.
    # Without these overrides both the PATH and LD_LIBRARY_PATH contain paths
    # in the part's install directory which binaries can be incompatible with
    # the ones running on our system.  We don't need those while running stage
    # and prime anyway.
    override-pull: |
      unset LD_LIBRARY_PATH;
      craftctl set version="$(/bin/date +%Y%m%d)"
      craftctl default
    override-stage: |
      craftctldir="$(dirname "$(command -v craftctl)")"
      unset LD_LIBRARY_PATH;
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
      # ensure craftctl is found, see
      # https://github.com/snapcore/snapcraft/pull/2251
      export PATH="$PATH:$craftctldir"
      craftctl default
    override-prime: |
      craftctldir="$(dirname "$(command -v craftctl)")"
      unset LD_LIBRARY_PATH;
      export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
      # ensure craftctl is found, see
      # https://github.com/snapcore/snapcraft/pull/2251
      export PATH="$PATH:$craftctldir"
      craftctl default
      # ensure build-in tests are run
      cd ${CRAFT_PART_SRC} && make test TESTDIR=${CRAFT_PRIME}
