#!/bin/bash

FILESYSTEMS=(
    /run/mnt/data
    /run/mnt/gadget
    /run/mnt/ubuntu-boot
    /run/mnt/ubuntu-save
    /run/mnt/ubuntu-seed
    /writable
)

for fs in "${FILESYSTEMS[@]}"; do
    if mountpoint -q "${fs}"; then
        mount --make-private "${fs}"
    fi
done
