name: Release manually snap

on:
  workflow_dispatch:
    inputs:
      variant:
        description: 'Build variant'
        required: true
        default: 'regular'
        type: choice
        options:
          - regular
          - cloud-init
          - fips

permissions:
  contents: write

jobs:
  build_release:
    runs-on: ubuntu-latest
    environment: store
    steps:
      - name: Build and release base to edge channel
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-rebuild-base@upload-changelog-to-gh-release
        with:
          build-variant: ${{ github.event.inputs.variant }}
          publish: false
          # TODO: set upload-changelog to true once core26 also has a changelog
          upload-changelog: ${{ github.ref_name != 'main' }}
