name: Release bases

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build_releases:
    strategy:
      fail-fast: false
      matrix:
        # main is currently core26
        base: [core22, core24, main]
        variant: [normal, fips, cloud-init]
        exclude:
          - base: main
            variant: fips
        exclude:
          - base: core22
            variant: cloud-init
        exclude:
          - base: core24
            variant: cloud-init
    runs-on: ubuntu-latest
    environment: store
    steps:
      - name: Build and release ${{ matrix.base }} to edge channel
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        uses: snapcore/system-snaps-cicd-tools/action-rebuild-base@main
        with:
          branch: ${{ matrix.base }}
          build-variant: ${{ matrix.variant }}
